name: Run Flight Scanner

env:
  SHEETY_AUTH: ${{ secrets.SHEETY_AUTH }}
  KIWI_API_KEY: ${{ secrets.KIWI_API_KEY }}
  EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
  EMAIL_APP_PWD: ${{ secrets.EMAIL_APP_PWD }}

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  workflow_dispatch:
    branches:
      - main

jobs:
  run:
    name: Build and push docker image into container registry
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: run main.py
        run: poetry run python flightscanner/main.py